services:
  - type: web
    name: finsmart-api
    env: node
    region: ohio
    plan: free
    buildCommand: cd apps/api && npm install --include=dev && npx prisma generate && npx prisma db push && npm run build
    startCommand: cd apps/api && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false # Debes colocar la URL de Supabase manualmente en el dashboard de Render
      - key: JWT_SECRET
        generateValue: true # Render generará un secreto seguro automáticamente
      - key: NODE_ENV
        value: production
